### ISSUE TITLE
Custom Domain

### ISSUE THREAD

**Issue by thetealpickle** [hmfaysal/Notepad#17]
I am having trouble adding my custom domain devdes.me to the site. I was able to add the CNAME and set up the DNS with my provide (NameCheap), but the page loads without any of the aesthetic layout and none of the links send me to a page not found or a 404 error. 

The original site name jessjeanjo.github.io/Notepad works, but I am unable to successfully change it to my custom domain.

**Comment by balrawat** [comment]
did you tried to add a file named 'CNAME' with the name of domain you want to serv.
That file should be in your repo root if you want custom domain.
hope it helps :)

**Comment by thetealpickle** [comment]
I tried that, but it didn't work. I just built my own, but thanks!
